name: videodownload
description: YouTube Video ve MP3 İndirici
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.2  
  dio: ^5.4.0                   
  path_provider: ^2.1.1         
  permission_handler: ^11.3.1
  # Hafif ve modern FFmpeg sürümü
  ffmpeg_kit_flutter_video: 6.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
