name: Flutter APK Oluşturucu

on:
  push:
    branches: [ main ] # Kod her güncellendiğinde çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          
      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          
      - name: Bağımlılıkları Yükle
        run: flutter pub get
        
      - name: APK Derle
        run: flutter build apk --release
        
      - name: APK'yı Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: uygulama-apk
          path: build/app/outputs/flutter-apk/app-release.apk
