name: Flutter APK Oluşturucu

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Getir
        uses: actions/checkout@v4
      
      - name: Java Kurulumu (Java 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Flutter Kurulumu (Uyumlu Sürüm)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # En sorunsuz sürüm
          
      - name: Yapılandırma Dosyalarını Hazırla
        run: |
          mkdir -p android
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
      - name: Paketleri Yükle
        run: flutter pub get
        
      - name: APK Oluştur (Release)
        run: flutter build apk --release
        
      - name: APK Dosyasını Yükle
        uses: actions/upload-artifact@v4
        with:
          name: uygulama-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
